### ISSUE TITLE
erpnext启动失败

### ISSUE THREAD

**Issue by JiewenGuan** [lvxj11/docker#10]
您好，我尝试在群晖的docker上运行如下脚本
# docker run -itd -p 47300:8000 -v /volume1/docker/erpNext/data:/var/lib/mysql   -v /volume1/docker/erpNext/sites:/home/frappe/frappe-bench/sites   --name ERPNext13 lvxj11/erpnext:latest
e965eef46a30f655cd0b28d423d6bc10f75dc9b5c0cc45d08d45e0ff362207de
然而容器启动后按端口号访问无响应，一分钟内自动停机，报错如下：
`ERPNext13
date,stream,content
2022-03-04 05:14:12,stdout,13:14:12 system           | redis_socketio.1 stopped (rc=-15)

2022-03-04 05:14:12,stdout,"[0m[33m13:14:12 redis_socketio.1 | [0m574:M 04 Mar 2022 13:14:12.445 # Redis is now ready to exit, bye bye...
"
2022-03-04 05:14:12,stdout,[0m[33m13:14:12 redis_socketio.1 | [0m574:M 04 Mar 2022 13:14:12.445 * Removing the pid file.

2022-03-04 05:14:12,stdout,[0m[33m13:14:12 redis_socketio.1 | [0m574:M 04 Mar 2022 13:14:12.445 # User requested shutdown...

2022-03-04 05:14:12,stdout,13:14:12 system           | web.1 stopped (rc=-15)

2022-03-04 05:14:12,stdout,13:14:12 system           | schedule.1 stopped (rc=-15)

2022-03-04 05:14:12,stdout,13:14:12 system           | worker_long.1 stopped (rc=-15)

2022-03-04 05:14:12,stdout,13:14:12 system           | worker_short.1 stopped (rc=-15)

2022-03-04 05:14:12,stdout,13:14:12 system           | worker_default.1 stopped (rc=-15)

2022-03-04 05:14:12,stdout,13:14:12 system           | watch.1 stopped (rc=-15)

2022-03-04 05:14:12,stdout,13:14:12 system           | redis_queue.1 stopped (rc=-15)

2022-03-04 05:14:12,stdout,"[0m[32m13:14:12 redis_queue.1    | [0m579:M 04 Mar 2022 13:14:12.358 # Redis is now ready to exit, bye bye...
"
2022-03-04 05:14:12,stdout,[0m[32m13:14:12 redis_queue.1    | [0m579:M 04 Mar 2022 13:14:12.358 * Removing the pid file.

2022-03-04 05:14:12,stdout,[0m[32m13:14:12 redis_queue.1    | [0m579:M 04 Mar 2022 13:14:12.358 # User requested shutdown...

2022-03-04 05:14:12,stdout,13:14:12 system           | redis_cache.1 stopped (rc=-15)

2022-03-04 05:14:12,stdout,"[0m[36m13:14:12 redis_cache.1    | [0m587:M 04 Mar 2022 13:14:12.355 # Redis is now ready to exit, bye bye...
"
2022-03-04 05:14:12,stdout,[0m[36m13:14:12 redis_cache.1    | [0m587:M 04 Mar 2022 13:14:12.355 * Removing the pid file.

2022-03-04 05:14:12,stdout,[0m[36m13:14:12 redis_cache.1    | [0m587:M 04 Mar 2022 13:14:12.355 # User requested shutdown...

2022-03-04 05:14:12,stdout,[0m[32m13:14:12 redis_queue.1    | [0m579:signal-handler (1646370852) Received SIGTERM scheduling shutdown...

2022-03-04 05:14:12,stdout,[0m[33m13:14:12 redis_socketio.1 | [0m574:signal-handler (1646370852) Received SIGTERM scheduling shutdown...

2022-03-04 05:14:12,stdout,[0m[36m13:14:12 redis_cache.1    | [0m587:signal-handler (1646370852) Received SIGTERM scheduling shutdown...

2022-03-04 05:14:12,stdout,13:14:12 system           | sending SIGTERM to worker_default.1 (pid 597)

2022-03-04 05:14:12,stdout,13:14:12 system           | sending SIGTERM to worker_long.1 (pid 585)

2022-03-04 05:14:12,stdout,13:14:12 system           | sending SIGTERM to worker_short.1 (pid 598)

2022-03-04 05:14:12,stdout,13:14:12 system           | sending SIGTERM to schedule.1 (pid 581)

2022-03-04 05:14:12,stdout,13:14:12 system           | sending SIGTERM to watch.1 (pid 599)

2022-03-04 05:14:12,stdout,13:14:12 system           | sending SIGTERM to web.1 (pid 583)

2022-03-04 05:14:12,stdout,13:14:12 system           | sending SIGTERM to redis_queue.1 (pid 572)

2022-03-04 05:14:12,stdout,13:14:12 system           | sending SIGTERM to redis_socketio.1 (pid 570)

2022-03-04 05:14:12,stdout,13:14:12 system           | sending SIGTERM to redis_cache.1 (pid 568)

2022-03-04 05:14:12,stdout,13:14:12 system           | socketio.1 stopped (rc=1)

2022-03-04 05:14:12,stdout,[0m[31m13:14:12 socketio.1       | [0m}

2022-03-04 05:14:12,stdout,[0m[31m13:14:12 socketio.1       | [0m  port: 12311

2022-03-04 05:14:12,stdout,"[0m[31m13:14:12 socketio.1       | [0m  address: '127.0.0.1',
"
2022-03-04 05:14:12,stdout,"[0m[31m13:14:12 socketio.1       | [0m  syscall: 'connect',
"
2022-03-04 05:14:12,stdout,"[0m[31m13:14:12 socketio.1       | [0m  code: 'ECONNREFUSED',
"
2022-03-04 05:14:12,stdout,"[0m[31m13:14:12 socketio.1       | [0m  errno: -111,
"
2022-03-04 05:14:12,stdout,[0m[31m13:14:12 socketio.1       | [0m    at processTicksAndRejections (internal/process/task_queues.js:82:21) {

2022-03-04 05:14:12,stdout,[0m[31m13:14:12 socketio.1       | [0m    at emitErrorCloseNT (internal/streams/destroy.js:74:3)

2022-03-04 05:14:12,stdout,[0m[31m13:14:12 socketio.1       | [0m    at emitErrorNT (internal/streams/destroy.js:106:8)

2022-03-04 05:14:12,stdout,[0m[31m13:14:12 socketio.1       | [0m    at Socket.emit (events.js:400:28)

2022-03-04 05:14:12,stdout,[0m[31m13:14:12 socketio.1       | [0m    at Socket.<anonymous> (/home/frappe/frappe-bench/apps/frappe/node_modules/redis/index.js:223:14)

2022-03-04 05:14:12,stdout,[0m[31m13:14:12 socketio.1       | [0m    at RedisClient.on_error (/home/frappe/frappe-bench/apps/frappe/node_modules/redis/index.js:342:14)

2022-03-04 05:14:12,stdout,[0m[31m13:14:12 socketio.1       | [0mEmitted 'error' event on RedisClient instance at:

2022-03-04 05:14:12,stdout,[0m[31m13:14:12 socketio.1       | [0m    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1159:16)

2022-03-04 05:14:12,stdout,[0m[31m13:14:12 socketio.1       | [0mError: connect ECONNREFUSED 127.0.0.1:12311

2022-03-04 05:14:12,stdout,[0m[31m13:14:12 socketio.1       | [0m

2022-03-04 05:14:12,stdout,[0m[31m13:14:12 socketio.1       | [0m      ^

2022-03-04 05:14:12,stdout,[0m[31m13:14:12 socketio.1       | [0m      throw er; // Unhandled 'error' event

2022-03-04 05:14:12,stdout,[0m[31m13:14:12 socketio.1       | [0mevents.js:377

2022-03-04 05:14:12,stdout,[0m[31m13:14:12 socketio.1       | [0mlistening on *: 3000

2022-03-04 05:14:11,stdout,[0m[34m13:14:11 watch.1          | [0m

2022-03-04 05:14:11,stdout,[0m[34m13:14:11 watch.1          | [0mOSError: b'./apps.txt' Not Found

2022-03-04 05:14:11,stdout,[0m[34m13:14:11 watch.1          | [0m    raise IOError("{} Not Found".format(path))

2022-03-04 05:14:11,stdout,"[0m[34m13:14:11 watch.1          | [0m  File \"/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py\", line 1187, in read_file
"
2022-03-04 05:14:11,stdout,"[0m[34m13:14:11 watch.1          | [0m    content = read_file(path, raise_not_found=raise_not_found)
"
2022-03-04 05:14:11,stdout,"[0m[34m13:14:11 watch.1          | [0m  File \"/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py\", line 1162, in get_file_items
"
2022-03-04 05:14:11,stdout,"[0m[34m13:14:11 watch.1          | [0m    apps = get_file_items(os.path.join(sites_path, \"apps.txt\"), raise_not_found=True)
"
2022-03-04 05:14:11,stdout,"[0m[34m13:14:11 watch.1          | [0m  File \"/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py\", line 1024, in get_all_apps
"
2022-03-04 05:14:11,stdout,"[0m[34m13:14:11 watch.1          | [0m    return frappe.get_all_apps(with_internal_apps=False, sites_path='.')
"
2022-03-04 05:14:11,stdout,"[0m[34m13:14:11 watch.1          | [0m  File \"/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py\", line 99, in get_apps
"
2022-03-04 05:14:11,stdout,[0m[34m13:14:11 watch.1          | [0m    for app in get_apps():

2022-03-04 05:14:11,stdout,"[0m[34m13:14:11 watch.1          | [0m  File \"/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py\", line 25, in get_app_groups
"
2022-03-04 05:14:11,stdout,[0m[34m13:14:11 watch.1          | [0m    commands = get_app_groups()

2022-03-04 05:14:11,stdout,"[0m[34m13:14:11 watch.1          | [0m  File \"/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py\", line 14, in main
"
2022-03-04 05:14:11,stdout,[0m[34m13:14:11 watch.1          | [0m    main()

2022-03-04 05:14:11,stdout,"[0m[34m13:14:11 watch.1          | [0m  File \"/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py\", line 104, in <module>
"
2022-03-04 05:14:11,stdout,"[0m[34m13:14:11 watch.1          | [0m    exec(code, run_globals)
"
2022-03-04 05:14:11,stdout,"[0m[34m13:14:11 watch.1          | [0m  File \"/usr/lib/python3.8/runpy.py\", line 87, in _run_code
"
2022-03-04 05:14:11,stdout,"[0m[34m13:14:11 watch.1          | [0m    return _run_code(code, main_globals, None,
"
2022-03-04 05:14:11,stdout,"[0m[34m13:14:11 watch.1          | [0m  File \"/usr/lib/python3.8/runpy.py\", line 194, in _run_module_as_main
"
2022-03-04 05:14:11,stdout,[0m[34m13:14:11 watch.1          | [0mTraceback (most recent call last):

2022-03-04 05:14:11,stdout,[0m[34m13:14:11 watch.1          | [0m  warnings.warn(

2022-03-04 05:14:11,stdout,[0m[34m13:14:11 watch.1          | [0m/home/frappe/frappe-bench/env/lib/python3.8/site-packages/bleach_whitelist/bleach_whitelist.py:3: DeprecationWarning: bleach-whitelist has been renamed bleach-allowlist. It will not receive further updates under the old name. See https://pypi.org/project/bleach-allowlist

2022-03-04 05:14:11,stdout,[0m[34m13:14:11 watch.1          | [0m  from imp import reload

2022-03-04 05:14:11,stdout,[0m[34m13:14:11 watch.1          | [0m/home/frappe/frappe-bench/env/lib/python3.8/site-packages/past/builtins/misc.py:45: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses

2022-03-04 05:14:11,stdout,[0m[36;1m13:14:11 schedule.1       | [0m

2022-03-04 05:14:11,stdout,[0m[36;1m13:14:11 schedule.1       | [0mOSError: b'./apps.txt' Not Found

2022-03-04 05:14:11,stdout,[0m[36;1m13:14:11 schedule.1       | [0m    raise IOError("{} Not Found".format(path))

2022-03-04 05:14:11,stdout,"[0m[36;1m13:14:11 schedule.1       | [0m  File \"/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py\", line 1187, in read_file
"
2022-03-04 05:14:11,stdout,"[0m[36;1m13:14:11 schedule.1       | [0m    content = read_file(path, raise_not_found=raise_not_found)
"
2022-03-04 05:14:11,stdout,"[0m[36;1m13:14:11 schedule.1       | [0m  File \"/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py\", line 1162, in get_file_items
"
2022-03-04 05:14:11,stdout,"[0m[36;1m13:14:11 schedule.1       | [0m    apps = get_file_items(os.path.join(sites_path, \"apps.txt\"), raise_not_found=True)
"
2022-03-04 05:14:11,stdout,"[0m[36;1m13:14:11 schedule.1       | [0m  File \"/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py\", line 1024, in get_all_apps
"
2022-03-04 05:14:11,stdout,"[0m[36;1m13:14:11 schedule.1       | [0m    return frappe.get_all_apps(with_internal_apps=False, sites_path='.')
"
2022-03-04 05:14:11,stdout,"[0m[36;1m13:14:11 schedule.1       | [0m  File \"/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py\", line 99, in get_apps
"
2022-03-04 05:14:11,stdout,[0m[36;1m13:14:11 schedule.1       | [0m    for app in get_apps():

2022-03-04 05:14:11,stdout,"[0m[36;1m13:14:11 schedule.1       | [0m  File \"/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py\", line 25, in get_app_groups
"
2022-03-04 05:14:11,stdout,[0m[36;1m13:14:11 schedule.1       | [0m    commands = get_app_groups()

2022-03-04 05:14:11,stdout,"[0m[36;1m13:14:11 schedule.1       | [0m  File \"/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py\", line 14, in main
"
2022-03-04 05:14:11,stdout,[0m[36;1m13:14:11 schedule.1       | [0m    main()

2022-03-04 05:14:11,stdout,"[0m[36;1m13:14:11 schedule.1       | [0m  File \"/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py\", line 104, in <module>
"
2022-03-04 05:14:11,stdout,"[0m[36;1m13:14:11 schedule.1       | [0m    exec(code, run_globals)
"
2022-03-04 05:14:11,stdout,"[0m[36;1m13:14:11 schedule.1       | [0m  File \"/usr/lib/python3.8/runpy.py\", line 87, in _run_code
"
2022-03-04 05:14:11,stdout,"[0m[36;1m13:14:11 schedule.1       | [0m    return _run_code(code, main_globals, None,
"
2022-03-04 05:14:11,stdout,"[0m[36;1m13:14:11 schedule.1       | [0m  File \"/usr/lib/python3.8/runpy.py\", line 194, in _run_module_as_main
"
2022-03-04 05:14:11,stdout,[0m[36;1m13:14:11 schedule.1       | [0mTraceback (most recent call last):

2022-03-04 05:14:11,stdout,[0m[36;1m13:14:11 schedule.1       | [0m  warnings.warn(

2022-03-04 05:14:11,stdout,[0m[36;1m13:14:11 schedule.1       | [0m/home/frappe/frappe-bench/env/lib/python3.8/site-packages/bleach_whitelist/bleach_whitelist.py:3: DeprecationWarning: bleach-whitelist has been renamed bleach-allowlist. It will not receive further updates under the old name. See https://pypi.org/project/bleach-allowlist

2022-03-04 05:14:11,stdout,[0m[36;1m13:14:11 schedule.1       | [0m  from imp import reload

2022-03-04 05:14:11,stdout,[0m[36;1m13:14:11 schedule.1       | [0m/home/frappe/frappe-bench/env/lib/python3.8/site-packages/past/builtins/misc.py:45: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses

2022-03-04 05:14:10,stdout,[0m[35m13:14:10 web.1            | [0m

2022-03-04 05:14:10,stdout,[0m[35m13:14:10 web.1            | [0mOSError: b'./apps.txt' Not Found

2022-03-04 05:14:10,stdout,[0m[35m13:14:10 web.1            | [0m    raise IOError("{} Not Found".format(path))

2022-03-04 05:14:10,stdout,"[0m[35m13:14:10 web.1            | [0m  File \"/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py\", line 1187, in read_file
"
2022-03-04 05:14:10,stdout,"[0m[35m13:14:10 web.1            | [0m    content = read_file(path, raise_not_found=raise_not_found)
"
2022-03-04 05:14:10,stdout,"[0m[35m13:14:10 web.1            | [0m  File \"/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py\", line 1162, in get_file_items
"
2022-03-04 05:14:10,stdout,"[0m[35m13:14:10 web.1            | [0m    apps = get_file_items(os.path.join(sites_path, \"apps.txt\"), raise_not_found=True)
"
2022-03-04 05:14:10,stdout,"[0m[35m13:14:10 web.1            | [0m  File \"/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py\", line 1024, in get_all_apps
"
2022-03-04 05:14:10,stdout,"[0m[35m13:14:10 web.1            | [0m    return frappe.get_all_apps(with_internal_apps=False, sites_path='.')
"
2022-03-04 05:14:10,stdout,"[0m[35m13:14:10 web.1            | [0m  File \"/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py\", line 99, in get_apps
"
2022-03-04 05:14:10,stdout,[0m[35m13:14:10 web.1            | [0m    for app in get_apps():

2022-03-04 05:14:10,stdout,"[0m[35m13:14:10 web.1            | [0m  File \"/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py\", line 25, in get_app_groups
"
2022-03-04 05:14:10,stdout,[0m[35m13:14:10 web.1            | [0m    commands = get_app_groups()

2022-03-04 05:14:10,stdout,"[0m[35m13:14:10 web.1            | [0m  File \"/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py\", line 14, in main
"
2022-03-04 05:14:10,stdout,[0m[35m13:14:10 web.1            | [0m    main()

2022-03-04 05:14:10,stdout,"[0m[35m13:14:10 web.1            | [0m  File \"/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py\", line 104, in <module>
"
2022-03-04 05:14:10,stdout,"[0m[35m13:14:10 web.1            | [0m    exec(code, run_globals)
"
2022-03-04 05:14:10,stdout,"[0m[35m13:14:10 web.1            | [0m  File \"/usr/lib/python3.8/runpy.py\", line 87, in _run_code
"
2022-03-04 05:14:10,stdout,"[0m[35m13:14:10 web.1            | [0m    return _run_code(code, main_globals, None,
"
2022-03-04 05:14:10,stdout,"[0m[35m13:14:10 web.1            | [0m  File \"/usr/lib/python3.8/runpy.py\", line 194, in _run_module_as_main
"
2022-03-04 05:14:10,stdout,[0m[35m13:14:10 web.1            | [0mTraceback (most recent call last):

2022-03-04 05:14:10,stdout,[0m[35m13:14:10 web.1            | [0m  warnings.warn(

2022-03-04 05:14:10,stdout,[0m[35m13:14:10 web.1            | [0m/home/frappe/frappe-bench/env/lib/python3.8/site-packages/bleach_whitelist/bleach_whitelist.py:3: DeprecationWarning: bleach-whitelist has been renamed bleach-allowlist. It will not receive further updates under the old name. See https://pypi.org/project/bleach-allowlist

2022-03-04 05:14:10,stdout,[0m[35m13:14:10 web.1            | [0m  from imp import reload

2022-03-04 05:14:10,stdout,[0m[35m13:14:10 web.1            | [0m/home/frappe/frappe-bench/env/lib/python3.8/site-packages/past/builtins/misc.py:45: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses

2022-03-04 05:14:09,stdout,13:14:09 system           | socketio.1 started (pid=592)

2022-03-04 05:14:09,stdout,13:14:09 system           | worker_default.1 started (pid=597)

2022-03-04 05:14:09,stdout,13:14:09 system           | watch.1 started (pid=599)

2022-03-04 05:14:09,stdout,[0m[36m13:14:09 redis_cache.1    | [0m587:M 04 Mar 2022 13:14:09.632 * Ready to accept connections

2022-03-04 05:14:09,stdout,[0m[36m13:14:09 redis_cache.1    | [0m587:M 04 Mar 2022 13:14:09.632 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.

2022-03-04 05:14:09,stdout,[0m[36m13:14:09 redis_cache.1    | [0m587:M 04 Mar 2022 13:14:09.632 # Server initialized

2022-03-04 05:14:09,stdout,[0m[36m13:14:09 redis_cache.1    | [0m587:M 04 Mar 2022 13:14:09.631 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.

2022-03-04 05:14:09,stdout,"[0m[36m13:14:09 redis_cache.1    | [0m587:M 04 Mar 2022 13:14:09.630 * Running mode=standalone, port=13000.
"
2022-03-04 05:14:09,stdout,13:14:09 system           | worker_short.1 started (pid=598)

2022-03-04 05:14:09,stdout,[0m[36m13:14:09 redis_cache.1    | [0m587:C 04 Mar 2022 13:14:09.627 # Configuration loaded

2022-03-04 05:14:09,stdout,"[0m[36m13:14:09 redis_cache.1    | [0m587:C 04 Mar 2022 13:14:09.627 # Redis version=5.0.7, bits=64, commit=00000000, modified=0, pid=587, just started
"
2022-03-04 05:14:09,stdout,[0m[36m13:14:09 redis_cache.1    | [0m587:C 04 Mar 2022 13:14:09.627 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo

2022-03-04 05:14:09,stdout,13:14:09 system           | web.1 started (pid=583)

2022-03-04 05:14:09,stdout,13:14:09 system           | worker_long.1 started (pid=585)

2022-03-04 05:14:09,stdout,13:14:09 system           | schedule.1 started (pid=581)

2022-03-04 05:14:09,stdout,[0m[33m13:14:09 redis_socketio.1 | [0m574:M 04 Mar 2022 13:14:09.618 * Ready to accept connections

2022-03-04 05:14:09,stdout,[0m[33m13:14:09 redis_socketio.1 | [0m574:M 04 Mar 2022 13:14:09.617 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.

2022-03-04 05:14:09,stdout,[0m[33m13:14:09 redis_socketio.1 | [0m574:M 04 Mar 2022 13:14:09.617 # Server initialized

2022-03-04 05:14:09,stdout,[0m[33m13:14:09 redis_socketio.1 | [0m574:M 04 Mar 2022 13:14:09.617 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.

2022-03-04 05:14:09,stdout,"[0m[33m13:14:09 redis_socketio.1 | [0m574:M 04 Mar 2022 13:14:09.616 * Running mode=standalone, port=12000.
"
2022-03-04 05:14:09,stdout,[0m[32m13:14:09 redis_queue.1    | [0m579:M 04 Mar 2022 13:14:09.615 * Ready to accept connections

2022-03-04 05:14:09,stdout,[0m[32m13:14:09 redis_queue.1    | [0m579:M 04 Mar 2022 13:14:09.615 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.

2022-03-04 05:14:09,stdout,[0m[32m13:14:09 redis_queue.1    | [0m579:M 04 Mar 2022 13:14:09.615 # Server initialized

2022-03-04 05:14:09,stdout,[0m[32m13:14:09 redis_queue.1    | [0m579:M 04 Mar 2022 13:14:09.614 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.

2022-03-04 05:14:09,stdout,"[0m[32m13:14:09 redis_queue.1    | [0m579:M 04 Mar 2022 13:14:09.614 * Running mode=standalone, port=11000.
"
2022-03-04 05:14:09,stdout,[0m[33m13:14:09 redis_socketio.1 | [0m574:C 04 Mar 2022 13:14:09.613 # Configuration loaded

2022-03-04 05:14:09,stdout,"[0m[33m13:14:09 redis_socketio.1 | [0m574:C 04 Mar 2022 13:14:09.613 # Redis version=5.0.7, bits=64, commit=00000000, modified=0, pid=574, just started
"
2022-03-04 05:14:09,stdout,[0m[32m13:14:09 redis_queue.1    | [0m579:C 04 Mar 2022 13:14:09.612 # Configuration loaded

2022-03-04 05:14:09,stdout,"[0m[32m13:14:09 redis_queue.1    | [0m579:C 04 Mar 2022 13:14:09.612 # Redis version=5.0.7, bits=64, commit=00000000, modified=0, pid=579, just started
"
2022-03-04 05:14:09,stdout,13:14:09 system           | redis_cache.1 started (pid=568)

2022-03-04 05:14:09,stdout,[0m[33m13:14:09 redis_socketio.1 | [0m574:C 04 Mar 2022 13:14:09.608 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo

2022-03-04 05:14:09,stdout,[0m[32m13:14:09 redis_queue.1    | [0m579:C 04 Mar 2022 13:14:09.606 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo

2022-03-04 05:14:09,stdout,13:14:09 system           | redis_queue.1 started (pid=572)

2022-03-04 05:14:09,stdout,13:14:09 system           | redis_socketio.1 started (pid=570)

2022-03-04 05:14:06,stdout,

2022-03-04 05:14:06,stdout,OSError: b'./apps.txt' Not Found

2022-03-04 05:14:06,stdout,    raise IOError("{} Not Found".format(path))

2022-03-04 05:14:06,stdout,"  File \"/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py\", line 1187, in read_file
"
2022-03-04 05:14:06,stdout,"    content = read_file(path, raise_not_found=raise_not_found)
"
2022-03-04 05:14:06,stdout,"  File \"/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py\", line 1162, in get_file_items
"
2022-03-04 05:14:06,stdout,"    apps = get_file_items(os.path.join(sites_path, \"apps.txt\"), raise_not_found=True)
"
2022-03-04 05:14:06,stdout,"  File \"/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py\", line 1024, in get_all_apps
"
2022-03-04 05:14:06,stdout,"    return frappe.get_all_apps(with_internal_apps=False, sites_path='.')
"
2022-03-04 05:14:06,stdout,"  File \"/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py\", line 99, in get_apps
"
2022-03-04 05:14:06,stdout,    for app in get_apps():

2022-03-04 05:14:06,stdout,"  File \"/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py\", line 25, in get_app_groups
"
2022-03-04 05:14:06,stdout,    commands = get_app_groups()

2022-03-04 05:14:06,stdout,"  File \"/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py\", line 14, in main
"
2022-03-04 05:14:06,stdout,    main()

2022-03-04 05:14:06,stdout,"  File \"/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py\", line 104, in <module>
"
2022-03-04 05:14:06,stdout,"    exec(code, run_globals)
"
2022-03-04 05:14:06,stdout,"  File \"/usr/lib/python3.8/runpy.py\", line 87, in _run_code
"
2022-03-04 05:14:06,stdout,"    return _run_code(code, main_globals, None,
"
2022-03-04 05:14:06,stdout,"  File \"/usr/lib/python3.8/runpy.py\", line 194, in _run_module_as_main
"
2022-03-04 05:14:06,stdout,Traceback (most recent call last):

2022-03-04 05:14:04,stdout, * Starting MariaDB database server mysqld       [80G 
[74G[[31mfail[39;49m]

2022-03-04 05:13:33,stdout, * Stopping MariaDB database server mysqld       [80G 
[74G[ OK ]

2022-03-04 05:13:33,stdout,Starting redis-server: redis-server.

2022-03-04 05:13:31,stdout,Stopping redis-server: redis-server.

`
请问应当如何解决？

**Comment by lvxj11** [comment]
时间太久了，抱歉。先关闭吧
